### ISSUE TITLE
SD Controller setting to prevent BSoD on first boot (when Windows is installed on the SD card)

### ISSUE THREAD

**Issue by GNU-Linuxer** [worproject/RPi-Windows-Drivers#11]
When user finished flashing SD card, upon first boot, user need to immediately enter UEFI setting, then go to RPi configuration, select "MAX" under CPU (to speed up set-up process), and select "Arasan SDHCI controller".

Then user should press yes to save changes, and on main menu, select reset option to re-power the Pi. Also, I would recommend user to unplug keyboard (and as much USB device as possible) until it's ready for interactive setup.

After enter to Windows Desktop, the user can visit UEFI setting to switch back to eMMC controller for a faster performance, and USB device can always stay plugged in during boot without any issue.

I suggest to bring this notice evident in the imager program, as it prevents BSoD on first boot and subsequent "Windows Setup could not configure..." error (which requires re-flash the SD card).

Windows version is 19041.508

**Comment by mariobalanica** [comment]
Did you choose GPT as the partition scheme?

**Comment by GNU-Linuxer** [comment]
Hello, I choose MBR partition scheme.

**Comment by mariobalanica** [comment]
What SD card are you using? Also the last log file from the imager would be useful.

**Comment by GNU-Linuxer** [comment]
Sandisk Extreme Pro (A2 speed class) 64GB, and unfortunately the log is deleted.

**Comment by CE1CECL** [comment]
might be related to https://github.com/raspberrypi/windows-drivers/issues/24

**Comment by mariobalanica** [comment]
Could be, but we don't know what kind of BSoD the author of this issue is getting.
I'm going to close this issue and continue the discussion in the upstream repository: https://github.com/raspberrypi/windows-drivers/issues/24

Note that the latest release (https://github.com/worproject/RPi-Windows-Drivers/releases) doesn't include the Arasan driver, so for testing purposes you'll want to use the previous version of the package.
